// app/api/generate-summary/route.ts
//
// Called by the client when the user clicks "Generate Summary" on a document.
// It forwards the request to the Python summarizer API using the async/callback
// flow so the browser is never blocked waiting for NER processing to finish.
//
// Environment variables required:
//   SUMMARIZER_API_URL             — base URL of the Python API (no trailing slash)
//                                    e.g. https://doc-summarizer-xxx-uc.a.run.app
//   NEXT_PUBLIC_CONVEX_SITE_URL    — your Convex HTTP URL
//                                    e.g. https://xxx.convex.cloud
//   SUMMARIZER_CALLBACK_SECRET     — shared secret between Next.js and Convex
//                                    to authenticate the callback. Generate with:
//                                    openssl rand -hex 32

import { NextResponse } from "next/server";

export const runtime = "nodejs";

// How long (ms) to wait for the Python API to accept the job.
// The actual NER processing happens asynchronously — this timeout only covers
// the initial POST that queues the job, which is fast (~500ms).
const QUEUE_TIMEOUT_MS = 15_000;

export async function POST(request: Request) {
  // ── Parse & validate request body ─────────────────────────────────────────
  let body: {
    documentId?: string;
    fileUrl?: string;
    filename?: string;
  };

  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Request body must be valid JSON." },
      { status: 400 }
    );
  }

  const { documentId, fileUrl, filename } = body;

  if (!documentId || typeof documentId !== "string") {
    return NextResponse.json(
      { error: "Missing or invalid documentId." },
      { status: 400 }
    );
  }

  if (!fileUrl || typeof fileUrl !== "string") {
    return NextResponse.json(
      { error: "Missing or invalid fileUrl." },
      { status: 400 }
    );
  }

  // ── Read env vars ──────────────────────────────────────────────────────────
  const summarizerApiUrl = process.env.SUMMARIZER_API_URL;
  if (!summarizerApiUrl) {
    console.error("[generate-summary] SUMMARIZER_API_URL is not set.");
    return NextResponse.json(
      { error: "Summarizer service is not configured." },
      { status: 503 }
    );
  }

  const convexSiteUrl = process.env.NEXT_PUBLIC_CONVEX_SITE_URL;
  if (!convexSiteUrl) {
    console.error("[generate-summary] NEXT_PUBLIC_CONVEX_SITE_URL is not set.");
    return NextResponse.json(
      { error: "Convex site URL is not configured." },
      { status: 503 }
    );
  }

  const callbackSecret = process.env.SUMMARIZER_CALLBACK_SECRET;
  if (!callbackSecret) {
    console.error("[generate-summary] SUMMARIZER_CALLBACK_SECRET is not set.");
    return NextResponse.json(
      { error: "Callback secret is not configured." },
      { status: 503 }
    );
  }

  // ── Build callback URL ─────────────────────────────────────────────────────
  // We embed both the documentId and a shared secret in the callback URL.
  // The Python API will POST its result to this URL when processing is done,
  // and Convex will verify the secret before updating the document.
  const callbackUrl =
    `${convexSiteUrl}/callback-summarizer` +
    `?docId=${encodeURIComponent(documentId)}` +
    `&secret=${encodeURIComponent(callbackSecret)}`;

  // ── Call the Python async endpoint ────────────────────────────────────────
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), QUEUE_TIMEOUT_MS);

  try {
    const res = await fetch(`${summarizerApiUrl}/api/v1/summarize/async`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        file_url: fileUrl,
        callback_url: callbackUrl,
        filename: filename ?? `${documentId}.docx`,
        include_raw_entities: false,
      }),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (!res.ok) {
      let detail = "";
      try {
        const errBody = await res.json();
        detail = errBody?.detail ?? errBody?.error ?? "";
      } catch {
        // ignore parse error
      }
      console.error(
        `[generate-summary] Python API returned ${res.status}: ${detail}`
      );
      return NextResponse.json(
        {
          error: `Summarizer API error (${res.status})${detail ? `: ${detail}` : "."}`,
        },
        { status: 502 }
      );
    }

    const data = await res.json();

    // job_id is the UUID generated by the Python API.
    // We don't need to store it — the documentId in the callback URL is
    // sufficient for Convex to know which document to update.
    console.log(
      `[generate-summary] Job queued: ${data.job_id} for document ${documentId}`
    );

    return NextResponse.json({
      ok: true,
      jobId: data.job_id,
      message: "Summary job queued. The result will appear automatically.",
    });
  } catch (err: any) {
    clearTimeout(timeoutId);

    if (err?.name === "AbortError") {
      console.error("[generate-summary] Request to Python API timed out.");
      return NextResponse.json(
        {
          error:
            "The summarizer service did not respond in time. Please try again.",
        },
        { status: 504 }
      );
    }

    console.error("[generate-summary] Unexpected error:", err);
    return NextResponse.json(
      { error: "Failed to reach the summarizer service." },
      { status: 502 }
    );
  }
}
